version: 40
jobs:
- name: ci
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
  - !CommandStep
    name: build and test
    runInContainer: true
    image: rust:1
    interpreter: !DefaultInterpreter
      commands: |
        cargo build --tests --locked
        cargo test --locked -- --skip _pg
    useTTY: false
  triggers:
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 0
  retryDelay: 30
  timeout: 5400
