local data = toml.parse('name = "assay"\ncount = 42\n')
assert.eq(data.name, "assay")
assert.eq(data.count, 42)
local encoded = toml.encode(data)
local data2 = toml.parse(encoded)
assert.eq(data2.name, "assay")
