local data = yaml.parse("name: assay\ncount: 42\n")
assert.eq(data.name, "assay")
assert.eq(data.count, 42)
local encoded = yaml.encode(data)
local data2 = yaml.parse(encoded)
assert.eq(data2.name, "assay")

local tagged = yaml.parse("job:\n  script:\n    - !reference [.anchor, script]\n")
assert.eq(tagged.job.script[1]["!reference"][1], ".anchor")
assert.eq(tagged.job.script[1]["!reference"][2], "script")
local stripped = yaml.parse("a: !custom {x: 1}\n", { tags = "strip" })
assert.eq(stripped.a.x, 1)
local standard = yaml.parse("s: !!str 1\n")
assert.eq(standard.s, "1")
local retagged = yaml.parse(yaml.encode(tagged))
assert.eq(retagged.job.script[1]["!reference"][1], ".anchor")
