-- services/nspawn/resources.lua
--
-- CPU + memory limits for an nspawn container, applied via a systemd
-- drop-in on the host-side `systemd-nspawn@<name>.service` unit.
--
--   /etc/systemd/system/systemd-nspawn@<name>.service.d/
--       sysops-resources.conf
--
-- Two limits today:
--   cpu_cores  — number, whole-or-fractional cores (rendered as CPUQuota=)
--   memory_gb  — number, gibibytes              (rendered as MemoryMax=)
--
-- Disk is intentionally not handled here — nspawn has no native disk
-- limit. Adding it requires either filesystem-level quotas or switching
-- the rootfs to a fixed-size .raw image (separate plan).

local priv = require("services.host.privilege")

local M = {}

local DROPIN_NAME = "sysops-resources.conf"

local function dropin_dir(name)
  return "/etc/systemd/system/systemd-nspawn@" .. name .. ".service.d"
end

local function dropin_path(name)
  return dropin_dir(name) .. "/" .. DROPIN_NAME
end

-- Single-arg shell-quote (single-quote wrapping with embedded ' escape).
local function shell_quote(s)
  if type(s) ~= "string" then return "''" end
  return "'" .. (s:gsub("'", [['"'"']])) .. "'"
end

local function elev_prefix()
  return priv.elevated_prefix or ""
end

--- Render the drop-in INI body. Returns nil when neither limit is set —
--- callers should treat that as "no drop-in needed; clear any existing".
function M.render(cpu_cores, memory_gb)
  local lines = {}
  if type(cpu_cores) == "number" and cpu_cores > 0 then
    -- CPUQuota=200% means 2 full cores. Fractional cores are fine
    -- (e.g. 0.5 → 50%); systemd accepts integers in the percent value
    -- so we round to two decimal places then strip trailing zeros.
    local pct = cpu_cores * 100
    -- format with up to 2 decimals, then strip trailing zeros / dot
    local s = string.format("%.2f", pct)
    s = s:gsub("0+$", ""):gsub("%.$", "")
    lines[#lines + 1] = "CPUQuota=" .. s .. "%"
  end
  if type(memory_gb) == "number" and memory_gb > 0 then
    -- systemd accepts integer + suffix (G = gibibyte). For fractional
    -- memory we convert to MiB.
    if memory_gb == math.floor(memory_gb) then
      lines[#lines + 1] = "MemoryMax=" .. tostring(math.floor(memory_gb)) .. "G"
    else
      local mib = math.floor(memory_gb * 1024 + 0.5)
      lines[#lines + 1] = "MemoryMax=" .. tostring(mib) .. "M"
    end
  end
  if #lines == 0 then return nil end
  return "# Generated by sysops — edit via the dashboard or remove this file\n"
      .. "# manually and run `sudo systemctl daemon-reload && sudo systemctl\n"
      .. "# restart systemd-nspawn@<name>` to apply.\n"
      .. "[Service]\n"
      .. table.concat(lines, "\n") .. "\n"
end

-- Format a CPU value (cores) as a CPUQuota= argument value. Two-decimal
-- precision; trailing zeros stripped. e.g. 0.5 → "50%", 2 → "200%".
local function cpu_arg(cores)
  local pct = cores * 100
  local s = string.format("%.2f", pct)
  s = s:gsub("0+$", ""):gsub("%.$", "")
  return s .. "%"
end

local function memory_arg(gb)
  if gb == math.floor(gb) then
    return tostring(math.floor(gb)) .. "G"
  end
  return tostring(math.floor(gb * 1024 + 0.5)) .. "M"
end

local UNIT_FOR = function(name)
  return "systemd-nspawn@" .. name .. ".service"
end

-- Apply CPU + memory live to a running unit via `systemctl set-property
-- --runtime`. Runtime drop-ins land at /run/systemd/system.control/<unit>.d/
-- and disappear on reboot, where our persistent /etc/ drop-in
-- (sysops-resources.conf) takes over — single source of truth for
-- persistence, set-property for live.
local function set_property_live(name, cpu_cores, memory_gb)
  local args = { UNIT_FOR(name) }
  args[#args + 1] = "CPUQuota=" .. cpu_arg(cpu_cores)
  args[#args + 1] = "MemoryMax=" .. memory_arg(memory_gb)

  local quoted = {}
  for _, a in ipairs(args) do quoted[#quoted + 1] = shell_quote(a) end
  local cmd = elev_prefix() .. "systemctl set-property --runtime "
    .. table.concat(quoted, " ")
  local r = shell.exec(cmd, {})
  if not r or r.status ~= 0 then
    -- A "Unit ... not loaded" error is benign when the container isn't
    -- running — there's nothing live to update; the persistent drop-in
    -- still takes effect on next start. Surface it as a non-fatal warn.
    local stderr = (r and r.stderr) or "unknown"
    if stderr:find("not loaded", 1, true) or stderr:find("not active", 1, true) then
      return { ok = true, live = false, note = "unit not running; persistent drop-in active on next start" }
    end
    return { ok = false, error = "set-property failed: " .. stderr }
  end
  return { ok = true, live = true }
end

-- Clear live runtime overrides (the /run/systemd/system.control/<unit>.d/
-- drop-ins set-property writes). systemctl set-property has no good "remove"
-- verb — `CPUQuota=infinity` is rejected by the CLI parser, and `CPUQuota=`
-- (empty) is brittle across systemd versions. The cleanest path is to
-- remove the runtime drop-in dir directly and daemon-reload so systemd
-- forgets the overrides. Idempotent.
local function clear_property_live(name)
  local prefix = elev_prefix()
  local dir = "/run/systemd/system.control/systemd-nspawn@" .. name .. ".service.d"
  -- rm -rf <dir>; rmdir is implicit. Wrapped in sh -c so it's a single sudo.
  local cmd = prefix .. ("sh -c %s"):format(
    shell_quote(("rm -rf %q"):format(dir)))
  local r = shell.exec(cmd, {})
  if not r or r.status ~= 0 then
    return { ok = false, error = "clear runtime drop-in failed: " .. ((r and r.stderr) or "unknown") }
  end
  local rr = shell.exec(prefix .. "systemctl daemon-reload", {})
  if not rr or rr.status ~= 0 then
    return { ok = false, error = "daemon-reload failed: " .. ((rr and rr.stderr) or "unknown") }
  end
  return { ok = true }
end

--- Read the current persistent limits from the /etc/ drop-in.
---
--- Parses CPUQuota= and MemoryMax= lines. Doesn't enforce that they
--- came from sysops — if an operator hand-edits the file we still
--- read what they wrote.
---
--- Returns:
---   { cpu_cores = N | nil, memory_gb = N | nil, present = bool }
function M.read(name)
  if type(name) ~= "string" or name == ""
     or not name:match("^[A-Za-z0-9._%-]+$") then
    return { cpu_cores = nil, memory_gb = nil, present = false }
  end
  local f = io.open(dropin_path(name), "r")
  if not f then
    return { cpu_cores = nil, memory_gb = nil, present = false }
  end
  local body = f:read("*a") or ""
  f:close()

  local cpu, mem
  for line in body:gmatch("[^\n]+") do
    local trimmed = line:gsub("^%s+", ""):gsub("%s+$", "")
    local cpu_val = trimmed:match("^CPUQuota%s*=%s*([%d.]+)%%")
    if cpu_val then
      local n = tonumber(cpu_val)
      if n then cpu = n / 100 end
    end
    -- MemoryMax accepts integer with K/M/G/T suffix (binary) per
    -- systemd.resource-control(5). Parse the common shapes.
    local mem_num, mem_suf = trimmed:match("^MemoryMax%s*=%s*([%d.]+)%s*([KMGTkmgt]?)")
    if mem_num then
      local n = tonumber(mem_num)
      if n then
        local s = (mem_suf or ""):upper()
        if s == "G" then mem = n
        elseif s == "M" then mem = n / 1024
        elseif s == "K" then mem = n / (1024 * 1024)
        elseif s == "T" then mem = n * 1024
        else mem = n / (1024 * 1024 * 1024)  -- raw bytes
        end
      end
    end
  end
  return { cpu_cores = cpu, memory_gb = mem, present = true }
end

--- Apply CPU + memory limits to `name`. Two-stage:
---
---   1. Persistent: write/remove /etc/.../sysops-resources.conf so the
---      limits survive `systemctl restart`, host reboot, daemon-reload.
---   2. Live: `systemctl set-property --runtime` so the limits take effect
---      immediately on the running unit (no restart, no downtime). The
---      runtime drop-in lives under /run/ and is wiped on reboot — the
---      persistent /etc/ drop-in takes over from there.
---
--- When both limits are nil/0, the persistent drop-in is removed and
--- live state is reset to `infinity` (no limit).
---
--- Returns:
---   { ok = true,  applied = "wrote"|"removed", live = bool, note? }
---   { ok = false, error = "..." }
function M.apply(name, cpu_cores, memory_gb)
  if type(name) ~= "string" or name == ""
     or not name:match("^[A-Za-z0-9._%-]+$") then
    return { ok = false, error = "invalid machine name" }
  end

  local body = M.render(cpu_cores, memory_gb)
  local path = dropin_path(name)
  local prefix = elev_prefix()

  if body == nil then
    -- Clearing path: remove persistent drop-in, then wipe runtime
    -- drop-ins so any prior live overrides go away too.
    local cleared = M.clear_persistent(name)
    if not cleared.ok then return cleared end
    local live = clear_property_live(name)
    if not live.ok then return live end
    return { ok = true, applied = "removed", live = true }
  end

  -- 1) Persistent.
  local tmp = "/tmp/sysops-resources-" .. name .. "." .. tostring(os.time())
  local ok_w, err_w = pcall(fs.write, tmp, body)
  if not ok_w then
    return { ok = false, error = "tempfile write: " .. tostring(err_w) }
  end
  local cmd = prefix .. ("install -D -m 0644 -o root -g root %s %s"):format(
    shell_quote(tmp), shell_quote(path))
  local r = shell.exec(cmd, {})
  pcall(fs.remove, tmp)
  if not r or r.status ~= 0 then
    return { ok = false, error = "install failed: " .. ((r and r.stderr) or "unknown") }
  end
  local rr = shell.exec(prefix .. "systemctl daemon-reload", {})
  if not rr or rr.status ~= 0 then
    return { ok = false, error = "daemon-reload failed: " .. ((rr and rr.stderr) or "unknown") }
  end

  -- 2) Live.
  local live = set_property_live(name, cpu_cores, memory_gb)
  if not live.ok then return live end

  return { ok = true, applied = "wrote", live = live.live, note = live.note }
end

--- Internal: remove the persistent drop-in only. Used by clear() and the
--- clearing branch of apply().
function M.clear_persistent(name)
  if type(name) ~= "string" or name == ""
     or not name:match("^[A-Za-z0-9._%-]+$") then
    return { ok = false, error = "invalid machine name" }
  end
  local prefix = elev_prefix()
  local dir = dropin_dir(name)
  local path = dropin_path(name)

  -- rm -f the file, then best-effort empty-dir cleanup.
  local cmd = prefix .. ("sh -c %s"):format(
    shell_quote(("rm -f %q && rmdir --ignore-fail-on-non-empty %q"):format(path, dir)))
  local r = shell.exec(cmd, {})
  if not r or r.status ~= 0 then
    return { ok = false, error = "clear failed: " .. ((r and r.stderr) or "unknown") }
  end
  local rr = shell.exec(prefix .. "systemctl daemon-reload", {})
  if not rr or rr.status ~= 0 then
    return { ok = false, error = "daemon-reload failed: " .. ((rr and rr.stderr) or "unknown") }
  end
  return { ok = true, applied = "removed" }
end

--- Public clear: remove persistent drop-in AND live-reset to infinity.
--- Same as apply(name, nil, nil) but kept as a named entry point for
--- the destroy flow, which doesn't care about the live state since the
--- unit is about to go away anyway.
function M.clear(name)
  return M.apply(name, nil, nil)
end

return M
